import = [ "~/.config/alacritty/gruvbox.toml" ]
live_config_reload = true

[font]
size = 12

[font.normal]
family = "JetBrainsMonoNL Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMonoNL Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMonoNL Nerd Font"
# style = "italic"
style = "Regular"

[font.bold_italic]
family = "JetBrainsMonoNL Nerd Font"
# style = "Bold Italic"
style = "Regular"

[scrolling]
history = 10_000
multiplier = 10

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"
save_to_clipboard = true

[window]
opacity = 1
dynamic_padding = false
decorations = "full"
startup_mode = "Windowed"

  [window.padding]
  x = 5
  y = 1

