- name: Install docker on debian
  hosts:
    - all
    - localhost
  become: true
  tasks:
    # - name: Remove
    # This remove was just added when there was some issue in the apt repository file format.
    #   ansible.builtin.file:
    #     state: absent
    #     path: /etc/apt/sources.list.d/docker.list
    - name: Ensure essentials
      ansible.builtin.apt:
        update_cache: true
        pkg:
          - ca-certificates
          - curl
    - name: Ensure /etc/apt/keyrings directory exists
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add Docker's official GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'
    - name: Add docker to the apt repository
      ansible.builtin.apt_repository:
        # repo: deb [arch={{ arch }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ codename }} stable
        repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian bookworm stable
        filename: docker
        state: present

    - name: Install packages
      ansible.builtin.apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        update_cache: true

    - name: Ensure group
      ansible.builtin.group:
        name: docker
    - name: Add user to docker
      ansible.builtin.user:
        name: admin
        append: true
        groups: docker
