- name: Install Fastfetch
  hosts: localhost
  vars:
    deb_file: https://github.com/fastfetch-cli/fastfetch/releases/download/2.11.0/fastfetch-linux-amd64.deb
    home: /home/kumarmo2
  tasks:
    - name: Ensure Softwares directory
      ansible.builtin.file:
        path: ~/softwares/
        state: directory
        mode: '0744'

    - name: Get deb file
      ansible.builtin.get_url:
        url: "{{ deb_file }}"
        dest: ~/softwares
        mode: '0744'

    - name: Install deb file
      become: true
      ansible.builtin.apt:
        deb: "{{ home }}/softwares/fastfetch-linux-amd64.deb"
        state: present
