- name: Rebuild vim
  hosts: localhost
  tasks:
    - name: Delete vim clone directory
      ansible.builtin.file:
        path: ~/dev/oss/vim
        state: absent

    - name: Delete vim binary
      become: true
      ansible.builtin.file:
        path: /usr/bin/vim
        state: absent

- name: Run Build vim Playbook
  ansible.builtin.import_playbook: vim.playbook.yaml


