#!/bin/sh

# Autostart
sxhkd &
killall polybar
polybar example &
pgrep -x sxhkd > /dev/null || sxhkd &
# swap escape and capslock
setxkbmap -option caps:swapescape
# tmux start-server &
# tmux new-session -s svc &
echo "hello"

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

# Config

declare -A gruvbox # associative array declaration.

gruvbox['red0']="#cc241d"
gruvbox['grey0']="#a89984"
gruvbox['purple0']="#b16286"

bspc config automatic_scheme spiral
bspc config border_width        1
bspc config window_gap          4

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc config active_border_color gruvbox['red0']

bspc config focused_border_color ${gruvbox['purple0']}
bspc config normal_border_color  ${gruvbox['grey0']}

# -a is for add.
# bspc rule -a Alacritty desktop='^9' state=tiled focus=on
bspc rule -a Brave-browser state=tiled focus=on
bspc rule -a librewolf desktop='^8' state=tiled focus=on
bspc rule -a dropdown sticky=on state=floating hidden=on
# alacritty --class dropdown

# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
# restore wallpaper using custom wallpaper rotation tool
wallpaper-rotation -m restore
