-- ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
-- ┃                 CachyOS Hyprland Configuration              ┃
-- ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

_G.mainMod = "SUPER"

-- ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
-- ┃                         Source Files                        ┃
-- ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
-- Source: ~/.config/hypr/config/animations.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("config.animations")
-- Source: ~/.config/hypr/config/autostart.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("config.autostart")
-- Source: ~/.config/hypr/config/decorations.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("config.decorations")
-- Source: ~/.config/hypr/config/environment.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("config.environment")
-- Source: ~/.config/hypr/config/input.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("config.input")
-- Source: ~/.config/hypr/config/keybinds.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("config.keybinds")
-- Source: ~/.config/hypr/config/monitor.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("config.monitor")
-- Source: ~/.config/hypr/config/variables.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("config.variables")
-- Source: ~/.config/hypr/config/windowrules.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("config.windowrules")
-- Source: ~/.config/hypr/config/workspacerules.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("config.workspacerules")

-- Modifying these configs can be done by creating a user defined config in the home directory, e.g.
--# ~/.config/hypr/config/user-config.conf
-- source = ~/.config/hypr/config/user-config.conf
