# shellcheck shell=bash
# Catppuccin (Macchiato) theme for tmux-powerline

# Separator characters
if patched_font_in_use 2>/dev/null; then
	TMUX_POWERLINE_SEPARATOR_LEFT_BOLD=''
	TMUX_POWERLINE_SEPARATOR_LEFT_THIN=''
	TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD=''
	TMUX_POWERLINE_SEPARATOR_RIGHT_THIN=''
else
	TMUX_POWERLINE_SEPARATOR_LEFT_BOLD='◀'
	TMUX_POWERLINE_SEPARATOR_LEFT_THIN='❮'
	TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD='▶'
	TMUX_POWERLINE_SEPARATOR_RIGHT_THIN='❯'
fi

# Base colors (Catppuccin Macchiato)
export TMUX_POWERLINE_DEFAULT_BACKGROUND_COLOR='#232136'
export TMUX_POWERLINE_DEFAULT_FOREGROUND_COLOR='#e0def4'
export TMUX_POWERLINE_DEFAULT_LEFTSIDE_SEPARATOR=''
export TMUX_POWERLINE_DEFAULT_RIGHTSIDE_SEPARATOR=''

# shellcheck disable=SC2128
if [ -z "$TMUX_POWERLINE_WINDOW_STATUS_CURRENT" ]; then
	TMUX_POWERLINE_WINDOW_STATUS_CURRENT=(
		"#[fg=#232136,bg=#7aa2f7,bold]"
		"$TMUX_POWERLINE_DEFAULT_LEFTSIDE_SEPARATOR"
		" #I#F "
		"$TMUX_POWERLINE_SEPARATOR_RIGHT_THIN"
		" #W "
		"#[fg=#7aa2f7,bg=${TMUX_POWERLINE_DEFAULT_BACKGROUND_COLOR}]"
		"$TMUX_POWERLINE_DEFAULT_LEFTSIDE_SEPARATOR"
	)
fi

# shellcheck disable=SC2128
if [ -z "$TMUX_POWERLINE_WINDOW_STATUS_STYLE" ]; then
	TMUX_POWERLINE_WINDOW_STATUS_STYLE=(
		"#[fg=#e0def4,bg=#6e6a86]"
	)
fi

# shellcheck disable=SC2128
if [ -z "$TMUX_POWERLINE_WINDOW_STATUS_FORMAT" ]; then
	TMUX_POWERLINE_WINDOW_STATUS_FORMAT=(
		"#[fg=#e0def4,bg=#6e6a86]"
		"  #I#{?window_flags,#F, } "
		"$TMUX_POWERLINE_SEPARATOR_RIGHT_THIN"
		" #W "
	)
fi

# shellcheck disable=SC1143,SC2128
if [ -z "$TMUX_POWERLINE_LEFT_STATUS_SEGMENTS" ]; then
	TMUX_POWERLINE_LEFT_STATUS_SEGMENTS=(
		"tmux_session_info #c4a7e7 #232136"
		"vcs_branch #9ece6a #232136"
	)
fi

# shellcheck disable=SC1143,SC2128
if [ -z "$TMUX_POWERLINE_RIGHT_STATUS_SEGMENTS" ]; then
	TMUX_POWERLINE_RIGHT_STATUS_SEGMENTS=(
		"pwd #f9e2af #232136"
		"date_day #6e6a86 #e0def4"
		"date #6e6a86 #e0def4 ${TMUX_POWERLINE_SEPARATOR_LEFT_THIN}"
		"time #6e6a86 #e0def4 ${TMUX_POWERLINE_SEPARATOR_LEFT_THIN}"
	)
fi