# shellcheck shell=bash
# Catppuccin (Latte) theme for tmux-powerline

# Separator characters
if patched_font_in_use 2>/dev/null; then
	TMUX_POWERLINE_SEPARATOR_LEFT_BOLD=''
	TMUX_POWERLINE_SEPARATOR_LEFT_THIN=''
	TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD=''
	TMUX_POWERLINE_SEPARATOR_RIGHT_THIN=''
else
	TMUX_POWERLINE_SEPARATOR_LEFT_BOLD='◀'
	TMUX_POWERLINE_SEPARATOR_LEFT_THIN='❮'
	TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD='▶'
	TMUX_POWERLINE_SEPARATOR_RIGHT_THIN='❯'
fi

# Base colors (Catppuccin Latte)
export TMUX_POWERLINE_DEFAULT_BACKGROUND_COLOR='#eff1f5'
export TMUX_POWERLINE_DEFAULT_FOREGROUND_COLOR='#4c4f69'
export TMUX_POWERLINE_DEFAULT_LEFTSIDE_SEPARATOR=''
export TMUX_POWERLINE_DEFAULT_RIGHTSIDE_SEPARATOR=''

# shellcheck disable=SC2128
if [ -z "$TMUX_POWERLINE_WINDOW_STATUS_CURRENT" ]; then
	TMUX_POWERLINE_WINDOW_STATUS_CURRENT=(
		"#[fg=#eff1f5,bg=#1e66f5,bold]"
		"$TMUX_POWERLINE_DEFAULT_LEFTSIDE_SEPARATOR"
		" #I#F "
		"$TMUX_POWERLINE_SEPARATOR_RIGHT_THIN"
		" #W "
		"#[fg=#1e66f5,bg=${TMUX_POWERLINE_DEFAULT_BACKGROUND_COLOR}]"
		"$TMUX_POWERLINE_DEFAULT_LEFTSIDE_SEPARATOR"
	)
fi

# shellcheck disable=SC2128
if [ -z "$TMUX_POWERLINE_WINDOW_STATUS_STYLE" ]; then
	TMUX_POWERLINE_WINDOW_STATUS_STYLE=(
		"#[fg=#4c4f69,bg=#9ca0b0]"
	)
fi

# shellcheck disable=SC2128
if [ -z "$TMUX_POWERLINE_WINDOW_STATUS_FORMAT" ]; then
	TMUX_POWERLINE_WINDOW_STATUS_FORMAT=(
		"#[fg=#4c4f69,bg=#9ca0b0]"
		"  #I#{?window_flags,#F, } "
		"$TMUX_POWERLINE_SEPARATOR_RIGHT_THIN"
		" #W "
	)
fi

# shellcheck disable=SC1143,SC2128
if [ -z "$TMUX_POWERLINE_LEFT_STATUS_SEGMENTS" ]; then
	TMUX_POWERLINE_LEFT_STATUS_SEGMENTS=(
		"tmux_session_info #8839ef #eff1f5"
		"vcs_branch #40a02b #eff1f5"
	)
fi

# shellcheck disable=SC1143,SC2128
if [ -z "$TMUX_POWERLINE_RIGHT_STATUS_SEGMENTS" ]; then
	TMUX_POWERLINE_RIGHT_STATUS_SEGMENTS=(
		"pwd #fe640b #eff1f5"
		"date_day #9ca0b0 #4c4f69"
		"date #9ca0b0 #4c4f69 ${TMUX_POWERLINE_SEPARATOR_LEFT_THIN}"
		"time #9ca0b0 #4c4f69 ${TMUX_POWERLINE_SEPARATOR_LEFT_THIN}"
	)
fi