# shellcheck shell=bash
# Gruvbox Dark theme for tmux-powerline

# Separator characters
if patched_font_in_use 2>/dev/null; then
	TMUX_POWERLINE_SEPARATOR_LEFT_BOLD=''
	TMUX_POWERLINE_SEPARATOR_LEFT_THIN=''
	TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD=''
	TMUX_POWERLINE_SEPARATOR_RIGHT_THIN=''
else
	TMUX_POWERLINE_SEPARATOR_LEFT_BOLD='◀'
	TMUX_POWERLINE_SEPARATOR_LEFT_THIN='❮'
	TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD='▶'
	TMUX_POWERLINE_SEPARATOR_RIGHT_THIN='❯'
fi

# Base colors (Gruvbox Dark)
export TMUX_POWERLINE_DEFAULT_BACKGROUND_COLOR='#282828'
export TMUX_POWERLINE_DEFAULT_FOREGROUND_COLOR='#ebdbb2'
export TMUX_POWERLINE_DEFAULT_LEFTSIDE_SEPARATOR=''
export TMUX_POWERLINE_DEFAULT_RIGHTSIDE_SEPARATOR=''

# shellcheck disable=SC2128
if [ -z "$TMUX_POWERLINE_WINDOW_STATUS_CURRENT" ]; then
	TMUX_POWERLINE_WINDOW_STATUS_CURRENT=(
		"#[fg=#282828,bg=#fabd2f,bold]"
		"$TMUX_POWERLINE_DEFAULT_LEFTSIDE_SEPARATOR"
		" #I#F "
		"$TMUX_POWERLINE_SEPARATOR_RIGHT_THIN"
		" #W "
		"#[fg=#fabd2f,bg=${TMUX_POWERLINE_DEFAULT_BACKGROUND_COLOR}]"
		"$TMUX_POWERLINE_DEFAULT_LEFTSIDE_SEPARATOR"
	)
fi

# shellcheck disable=SC2128
if [ -z "$TMUX_POWERLINE_WINDOW_STATUS_STYLE" ]; then
	TMUX_POWERLINE_WINDOW_STATUS_STYLE=(
		"#[fg=#ebdbb2,bg=#3c3836]"
	)
fi

# shellcheck disable=SC2128
if [ -z "$TMUX_POWERLINE_WINDOW_STATUS_FORMAT" ]; then
	TMUX_POWERLINE_WINDOW_STATUS_FORMAT=(
		"#[fg=#ebdbb2,bg=#3c3836]"
		"  #I#{?window_flags,#F, } "
		"$TMUX_POWERLINE_SEPARATOR_RIGHT_THIN"
		" #W "
	)
fi

# shellcheck disable=SC1143,SC2128
if [ -z "$TMUX_POWERLINE_LEFT_STATUS_SEGMENTS" ]; then
	TMUX_POWERLINE_LEFT_STATUS_SEGMENTS=(
		"tmux_session_info #d3869b #282828"
		"vcs_branch #b8bb26 #282828"
	)
fi

# shellcheck disable=SC1143,SC2128
if [ -z "$TMUX_POWERLINE_RIGHT_STATUS_SEGMENTS" ]; then
	TMUX_POWERLINE_RIGHT_STATUS_SEGMENTS=(
		"pwd #fabd2f #282828"
		"date_day #3c3836 #ebdbb2"
		"date #3c3836 #ebdbb2 ${TMUX_POWERLINE_SEPARATOR_LEFT_THIN}"
		"time #3c3836 #ebdbb2 ${TMUX_POWERLINE_SEPARATOR_LEFT_THIN}"
	)
fi