-- ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
-- ┃                    Autostart Configuration                  ┃
-- ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- Source: ~/.config/hypr/config/defaults.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("config.defaults")

-- Autostart wiki https://wiki.hyprland.org/0.45.0/Configuring/Keywords/#executing #

-- exec-once = swaybg -o \* -i /usr/share/wallpapers/cachyos-wallpapers/Skyscraper.png -m fill
-- exec-once = mako &

-- ## Slow app launch fix

-- ## Idle configuration
-- exec-once = $idlehandler

hl.on("hyprland.start", function()
    local sig = os.getenv("HYPRLAND_INSTANCE_SIGNATURE") or ""

    hl.exec_cmd("hyprpanel &")
    hl.exec_cmd("fcitx5 -d &")
    hl.exec_cmd("nm-applet --indicator &")
    hl.exec_cmd("bash -c \"mkfifo /tmp/" .. sig .. ".wob && tail -f /tmp/" .. sig .. ".wob | wob & disown\" &")
    hl.exec_cmd("/usr/lib/polkit-kde-authentication-agent-1 &")
    hl.exec_cmd("systemctl --user import-environment &")
    hl.exec_cmd("hash dbus-update-activation-environment 2>/dev/null &")
    hl.exec_cmd("dbus-update-activation-environment --systemd &")
    hl.exec_cmd("hyprpaper &")
    hl.exec_cmd("~/dotfiles/bin/tmux-startup.sh &")
end)

