-- ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
-- ┃                      Colors Configuration                   ┃
-- ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

_G.cachylgreen = "rgba(82dcccff)"
_G.cachymgreen = "rgba(00aa84ff)"
_G.cachydgreen = "rgba(007d6fff)"
_G.cachylblue = "rgba(01ccffff)"
_G.cachymblue = "rgba(182545ff)"
_G.cachydblue = "rgba(111826ff)"
_G.cachywhite = "rgba(ffffffff)"
_G.cachygrey = "rgba(ddddddff)"
_G.cachygray = "rgba(798bb2ff)"
