-- ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
-- ┃                    Decorations Configuration                ┃
-- ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- Source: ~/.config/hypr/config/colors.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("config.colors")

-- https://wiki.hyprland.org/0.45.0/Configuring/Variables/#decoration

hl.config({
    decoration = {
        active_opacity = 1,
        rounding = 4,
        -- https://wiki.hyprland.org/0.45.0/Configuring/Variables/#blur
        blur = {
            size = 15,
            passes = 2, -- more passes = more resource intensive.
            xray = true,
        },
        -- https://wiki.hyprland.org/0.45.0/Configuring/Variables/#shadow
        shadow = {
            enabled = false,
        },
    },
    animations = {
        enabled = false,
    },
})

