-- ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
-- ┃                     Defaults Configuration                  ┃
-- ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

_G.filemanager = "ya"
-- $applauncher = rofi -show combi -modi window,run,combi -combi-modi window,run
_G.applauncher = "~/.config/rofi/launchers/type-6/launcher.sh"
_G.shutdownlauncher = "~/.config/rofi/powermenu/type-1/powermenu.sh"
_G.terminal = "kitty"
_G.idlehandler = "swayidle -w timeout 300 'swaylock -f -c 000000' before-sleep 'swaylock -f -c 000000'"
_G.capturing = "grim -g \"$(slurp)\" - | swappy -f -"
