-- ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
-- ┃                    Enviroment Configuration                 ┃
-- ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- Note: 'envd' (systemd/D-Bus-propagated) becomes a regular hl.env in Lua. If you relied on D-Bus propagation, set the variable via systemctl --user import-environment as a separate step.
hl.env("HYPRCURSOR_SIZE", "24")
-- Note: 'envd' (systemd/D-Bus-propagated) becomes a regular hl.env in Lua. If you relied on D-Bus propagation, set the variable via systemctl --user import-environment as a separate step.
hl.env("XCURSOR_SIZE", "24")
-- Note: 'envd' (systemd/D-Bus-propagated) becomes a regular hl.env in Lua. If you relied on D-Bus propagation, set the variable via systemctl --user import-environment as a separate step.
hl.env("QT_CURSOR_SIZE", "24")
