-- ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
-- ┃                      Input Configuration                    ┃
-- ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

-- Input wiki https://wiki.hyprland.org/0.45.0/Configuring/Variables/#input

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.config({
    input = {
        follow_mouse = 2, -- 0|1|2|3
        float_switch_override_focus = 2,
    },
})

