-- ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
-- ┃                     Monitor Configuration                   ┃
-- ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

-- Monitor wiki https://wiki.hyprland.org/0.45.0/Configuring/Monitors/

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
    output = "DP-1",
    mode = "3840x2160@143.85Hz",
    position = "0x0",
    scale = "1.20",
})

-- If you need to scale things like steam etc, please uncomment these lines.
-- Adjust GDK_SCALE accordingly to your liking.

hl.config({
    xwayland = {
        force_zero_scaling = true, -- Unscale XWayland
    },
    --env = GDK_SCALE, 1.25                   # GDK Scaling Factor
})

