-- ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
-- ┃                    Variables Configuration                  ┃
-- ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- Source: ~/.config/hypr/config/colors.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("config.colors")

-- Variables wiki https://wiki.hyprland.org/0.45.0/Configuring/Variables/ #
-- https://wiki.hyprland.org/0.45.0/Configuring/Variables/#general

hl.config({
  general = {
    gaps_in = 3,
    gaps_out = 5,
    border_size = 3,
    col = {
      active_border = cachylgreen,
      inactive_border = cachymblue,
    },
    layout = "dwindle", -- master|dwindle
    -- https://wiki.hyprland.org/0.45.0/Configuring/Variables/#snap
    snap = {
      enabled = true,
    },
  },
  -- https://wiki.hyprland.org/0.45.0/Configuring/Variables/#gestures
  -- https://wiki.hyprland.org/0.45.0/Configuring/Variables/#group
  group = {
    col = {
      border_active = cachydgreen,
      border_inactive = cachylgreen,
      border_locked_active = cachymgreen,
      border_locked_inactive = cachydblue,
    },
    -- https://wiki.hyprland.org/0.45.0/Configuring/Variables/#groupbar
    groupbar = {
      font_family = "Fira Sans",
      text_color = cachydblue,
      col = {
        active = cachydgreen,
        inactive = cachylgreen,
        locked_active = cachymgreen,
        locked_inactive = cachydblue,
      },
    },
  },
  -- https://wiki.hyprland.org/0.45.0/Configuring/Variables/#misc
  misc = {
    font_family = "Fira Sans",
    splash_font_family = "Fira Sans",
    disable_hyprland_logo = true,
    col = {
      splash = cachylgreen,
    },
    background_color = cachydblue,
    enable_swallow = true,
    swallow_regex = "^(cachy-browser|firefox|nautilus|nemo|thunar|btrfs-assistant.)$",
    focus_on_activate = true,
    vrr = 2,
  },
  -- https://wiki.hyprland.org/0.45.0/Configuring/Variables/#render
  render = {
    direct_scanout = true,
  },
  -- See https://wiki.hyprland.org/0.45.0/Configuring/Dwindle-Layout/ for more
  dwindle = {
    special_scale_factor = 0.8,
    -- pseudotile = true # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true,
  },
  -- See https://wiki.hyprland.org/0.45.0/Configuring/Master-Layout/ for more
  master = {
    new_status = "master",
    special_scale_factor = 0.8,
  },
})
