-- ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
-- ┃                    Windowrules Configuration                ┃
-- ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

-- Windows Rules https://wiki.hyprland.org/0.45.0/Configuring/Window-Rules/ #

-- Float Necessary Windows
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.window_rule({
    match = {
        class = "^(org.pulseaudio.pavucontrol)",
    },
    float = true,
})

hl.window_rule({
    match = {
        title = "^(Picture in picture)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        title = "^(Save File)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        title = "^(Open File)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^(blueman-manager)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^(xdg-desktop-portal-gtk|xdg-desktop-portal-kde|xdg-desktop-portal-hyprland)(.*)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^(polkit-gnome-authentication-agent-1|hyprpolkitagent|org.org.kde.polkit-kde-authentication-agent-1)(.*)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^(CachyOSHello)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^(zenity)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        title = "^(Steam - Self Updater)$",
    },
    float = true,
})

-- Increase the opacity
hl.window_rule({
    match = {
        class = "class:^(thunar|nemo)$",
    },
    opacity = 0.92,
})

hl.window_rule({
    match = {
        class = "^(discord|vesktop|armcord|webcord)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        title = "^(discord|vesktop|rmcord|webcord)$",
    },
    workspace = "4",
})

hl.window_rule({
    match = {
        title = "zen",
    },
    workspace = "2",
})

-- windowrule = match:title kitty, workspace 1
hl.window_rule({
    match = {
        title = "obsidian",
    },
    workspace = "3",
})

hl.window_rule({
    match = {
        class = "^DBeaver$",
    },
    workspace = "3",
})

hl.window_rule({
    match = {
        title = "title ^(QQ|Telegram)$",
        title = "^(QQ|Telegram)$",
    },
    opacity = 0.95,
})

hl.window_rule({
    match = {
        title = "^(NetEase Cloud Music Gtk4)$",
    },
    opacity = 0.95,
})

-- General window rules
hl.window_rule({
    match = {
        title = "^(Picture-in-Picture)$",
    },
    float = true,
    size = "960 540",
})

-- windowrule = move 25%-, title:^(Picture-in-Picture)$
hl.window_rule({
    match = {
        title = "^(imv|mpv|danmufloat|termfloat|nemo|ncmpcpp)$",
    },
    float = true,
})

-- windowrule = move 25%-, title:^(imv|mpv|danmufloat|termfloat|nemo|ncmpcpp)$
hl.window_rule({
    match = {
        title = "^(imv|mpv|danmufloat|termfloat|nemo|ncmpcpp)$",
    },
    size = "960 540",
})

hl.window_rule({
    match = {
        title = "^(danmufloat)$",
    },
    pin = true,
})

hl.window_rule({
    match = {
        title = "^(danmufloat|termfloat)$",
    },
    rounding = 5,
})

hl.window_rule({
    match = {
        title = "^(kitty|Alacritty)$",
    },
    animation = "slide right",
})

hl.window_rule({
    match = {
        title = "^(org.mozilla.firefox)$",
    },
    no_blur = true,
})

-- Decorations related to floating windows on workspaces 1 to 10
-- windowrule = bordersize 2, floating:1, onworkspace:w[fv1-10]
-- windowrule = bordercolor $cachylblue, floating:1, onworkspace:w[fv1-10]
-- windowrule = rounding 8, floating:1, onworkspace:w[fv1-10]
-- # Decorations related to tiling windows on workspaces 1 to 10
-- windowrule = bordersize 3, floating:0, onworkspace:f[1-10]
-- windowrule = rounding 4, floating:0, onworkspace:f[1-10]
-- Windows Rules End #

-- Workspaces Rules https://wiki.hyprland.org/0.45.0/Configuring/Workspace-Rules/ #
-- workspace = 1, default:true, monitor:$priMon
-- workspace = 6, default:true, monitor:$secMon
-- Workspace selectors https://wiki.hyprland.org/0.45.0/Configuring/Workspace-Rules/#workspace-selectors
-- workspace = r[1-5], monitor:$priMon
-- workspace = r[6-10], monitor:$secMon
-- workspace = special:scratchpad, on-created-empty:$applauncher
-- no_gaps_when_only deprecated instead workspaces rules with selectors can do the same
-- Smart gaps from 0.45.0 https://wiki.hyprland.org/0.45.0/Configuring/Workspace-Rules/#smart-gaps
hl.workspace_rule({
    workspace = "w[tv1-10]",
    gaps_out = 5,
    gaps_in = 3,
})

hl.workspace_rule({
    workspace = "f[1]",
    gaps_out = 5,
    gaps_in = 3,
})

-- Workspaces Rules End #

-- Layers Rules #
-- layerrule = animation slide top, logout_dialog
-- # layerrule = animation popin 50%, waybar
-- layerrule = animation slide down, waybar
-- layerrule = animation fade 50%, wallpaper
-- Layers Rules End #
